// <auto-generated />
using System;
using AravindReddy_K_301101869.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AravindReddy_K_301101869.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200324211312_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AravindReddy_K_301101869.Models.Club", b =>
                {
                    b.Property<string>("clubName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<int?>("nDraws");

                    b.Property<int?>("nWins");

                    b.Property<string>("nation");

                    b.Property<string>("sponsor");

                    b.Property<int?>("totalPoints");

                    b.HasKey("clubName");

                    b.ToTable("clubitems");
                });

            modelBuilder.Entity("AravindReddy_K_301101869.Models.Player", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Club");

                    b.Property<int>("JersyNumber");

                    b.Property<int>("Rank");

                    b.Property<int>("totalGoals");

                    b.HasKey("Name");

                    b.ToTable("playeritems");
                });

            modelBuilder.Entity("AravindReddy_K_301101869.Models.PlayersinClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("clubName");

                    b.Property<string>("playerName");

                    b.HasKey("Id");

                    b.HasIndex("clubName");

                    b.HasIndex("playerName");

                    b.ToTable("PlayersinClub");
                });

            modelBuilder.Entity("AravindReddy_K_301101869.Models.PlayersinClub", b =>
                {
                    b.HasOne("AravindReddy_K_301101869.Models.Club")
                        .WithMany("clubPlayers")
                        .HasForeignKey("clubName");

                    b.HasOne("AravindReddy_K_301101869.Models.Player", "player")
                        .WithMany()
                        .HasForeignKey("playerName");
                });
#pragma warning restore 612, 618
        }
    }
}
